Northwind_MvcUI/Models/ViewModels/ListProductsViewModel.cs
using Northwind_Entities.Concretes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Northwind_MvcUI.Models.ViewModels
{
    public class ListProductsViewModel
    {
        public List<Product> Products { get; set; }
    }
}

Northwind_MvcUI/Models/ViewModels/ProductManiViewModel.cs
using Northwind_Entities.Concretes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Northwind_MvcUI.Models.ViewModels
{
    public class ProductManiViewModel
    {
        public Product Product { get; set; }
        public List<Category> Categories { get; set; }
        public string ButtonName { get; set; }
    }
}

Northwind_MvcUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Northwind_Business.Abstracts;
using Northwind_Entities.Concretes;
using Northwind_MvcUI.Models.ViewModels;

namespace Northwind_MvcUI.Controllers
{
    public class HomeController : Controller
    {
        IProductService _productManager;
        ICategoryService _categoryManager;

        public HomeController(IProductService productService,ICategoryService categoryService)
        {
            _productManager = productService;
            _categoryManager = categoryService;
        }

        [HttpGet]
        public IActionResult ListMyProducts()
        {
            ListProductsViewModel model = new ListProductsViewModel
            {
                Products = _productManager.GetProducts()
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult AddMyProduct()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddMyProduct(Product product)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            _productManager.AddProduct(product);

            TempData["message"] = "Veri eklendi";

            return RedirectToAction("ListMyProducts");
        }

        [HttpGet]
        public IActionResult UpdateMyProduct(int id)
        {
            return View(id);
        }

        [HttpPost]
        public IActionResult UpdateMyProduct(Product product)
        {
            if (!ModelState.IsValid)
            {
                return View(product.ProductID);
            }

            _productManager.UpdateProduct(product);

            TempData["message"] = "Veri guncellendi";

            return RedirectToAction("ListMyProducts");
        }

        [HttpGet]
        public IActionResult DeleteMyProduct(int id)
        {
            _productManager.DeleteProduct(id);

            TempData["message"] = "Veri silindi";

            return RedirectToAction("ListMyProducts");
        }
    }
}

Northwind_MvcUI/ViewComponents/ProductManiViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Northwind_Business.Abstracts;
using Northwind_MvcUI.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Northwind_MvcUI.ViewComponents
{
    public class ProductManiViewComponent:ViewComponent
    {
        IProductService _productManager;
        ICategoryService _categoryManager;

        public ProductManiViewComponent(IProductService productService, ICategoryService categoryService)
        {
            _productManager = productService;
            _categoryManager = categoryService;
        }

        public ViewViewComponentResult Invoke(int id = 0)
        {
            ProductManiViewModel model = new ProductManiViewModel();
            model.Categories = _categoryManager.GetCategories();

            if (id == 0)
            {
                model.Product = new Northwind_Entities.Concretes.Product();
                model.ButtonName = "Add Product";
            }
            else
            {
                model.Product = _productManager.GetProduct(id);
                model.ButtonName = "Update Product";
            }

            return View(model);
        }
    }
}

Northwind_MvcUI/Views/Home/AddMyProduct.cshtml
@{
    ViewBag.Title = "AddMyProduct";
}

<h2>AddMyProduct</h2>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="AddMyProduct">
            @await  Component.InvokeAsync("ProductMani")
        </form>
    </div>
</div>

Northwind_MvcUI/Views/Home/ListMyProducts.cshtml
@model Northwind_MvcUI.Models.ViewModels.ListProductsViewModel

@{
    ViewBag.Title = "ListMyProducts";
}

<h2>ListMyProducts</h2>
<hr />

@if (TempData["message"] != null)
{
    <div class="alert alert-info">@TempData["message"]</div>
}

<table class="table table-responsive">
    <thead>
        <tr>
            <th>Product Name</th>
            <th>Category Name</th>
            <th>Unit Price</th>
            <th>Units In Stock</th>
            <th colspan="2"><a asp-action="AddMyProduct" asp-controller="Home" class="btn btn-block btn-default">Add Product</a></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Products)
        {
            <tr>
                <td>@item.ProductName</td>
                <td>@(item.CategoryId == null ? "No Category":item.Category.CategoryName)</td>
                <td>@item.UnitPrice.ToString("C2")</td>
                <td>@item.UnitsInStock</td>
                <td><a asp-action="UpdateMyProduct" asp-controller="Home" asp-route-id="@item.ProductID" class="btn btn-xs btn-primary">Update</a></td>
                <td><a asp-action="DeleteMyProduct" asp-controller="Home" asp-route-id="@item.ProductID" class="btn btn-xs btn-danger">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

Northwind_MvcUI/Views/Home/UpdateMyProduct.cshtml
@model int

@{
    ViewBag.Title = "UpdateMyProduct";
}

<h2>UpdateMyProduct</h2>
<hr />

<div class="row">
    <div class="col-md-6">
        <form asp-action="UpdateMyProduct" asp-controller="Home" method="post">
            @await Component.InvokeAsync("ProductMani",new { id = Model})
        </form>
    </div>
</div>

Northwind_MvcUI/Views/Shared/Components/ProductMani/Default.cshtml
@model Northwind_MvcUI.Models.ViewModels.ProductManiViewModel

@if (Model.Product.ProductID != 0)
{
    <input type="hidden" asp-for="@Model.Product.ProductID"/>
}

<div class="form-group">
    <label asp-for="Product.ProductName" class="control-label"></label>
    <input asp-for="Product.ProductName" class="form-control" />
    <span asp-validation-for="Product.ProductName" class="text-danger"></span>
</div>
<div class="form-group">
    <label class="control-label">CategoryName</label>
    <select asp-for="Product.CategoryId" class="form-control" asp-items='new SelectList(Model.Categories,"CategoryID","CategoryName")'></select>
</div>
<div class="form-group">
    <label asp-for="Product.UnitPrice" class="control-label"></label>
    <input asp-for="Product.UnitPrice" class="form-control" />
    <span asp-validation-for="Product.UnitPrice" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Product.UnitsInStock" class="control-label"></label>
    <input asp-for="Product.UnitsInStock" class="form-control" />
    <span asp-validation-for="Product.UnitsInStock" class="text-danger"></span>
</div>
<div class="form-group">
    <input type="submit" value="@Model.ButtonName" class="btn btn-default btn-block" />
</div>

Northwind_MvcUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <div>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Brand</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                        <li><a href="#">Link</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-left">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Link</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
    <div class="col-md-12">
        @RenderBody()
    </div>
</body>
</html>